# Generated by Django 3.0.5 on 2020-04-28 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_players_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='bottom_tile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='down_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='inside_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='item_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='left_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='outside_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='right_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='season_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='top_tile',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='up_id',
            field=models.IntegerField(default=0),
        ),
    ]
