# Generated by Django 3.0.5 on 2020-04-28 22:24

from django.db import migrations

def seed_seas_items(apps, schema_editor):
    Season = apps.get_model('main', 'Season')
    Items = apps.get_model('main', 'Items')
    items=[(1, 'Christmas Tree', 'A decorative tree fo celebrating a holiday.'), (2, 'Egg', 'A Colorfully died egg.'), (3, 'Fireworks', 'Hehe, firework go boom'), (4, 'Pumpkin', 'Pumpkin for your delicious seasonal recipes.')]
    seasons = ['winter','spring','summer','fall']
    for i in seasons:
        season = Season(name=i, is_solved=False)
        season.save()
    for i in items:
        item = Items(season_id=i[0], name=i[1], description=i[2])
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20200428_2045'),
    ]

    operations = [
        migrations.RunPython(seed_seas_items)
    ]
